---

- name: Get s3cmd pkg from github
  git:
    accept_hostkey: "yes"
    repo: "{{ s3cmd_repo }}"
    dest: "{{ s3cmd_dest }}"
    version: "{{ s3cmd_version }}"
    force: yes
    update: yes
  become: true

- name: Run installation script
  command: python3 setup.py install
  #sudo_user: "{{ sudo_user }}"
  args:
    chdir: "{{ s3cmd_dest }}"
    creates: "/usr/local/bin/s3cmd"
  become: true