---
# tasks file for s3cmd

- name: set fact for packages (git)
  set_fact:
     s3cmd_pkgs: "{{ s3cmd_pkgs_git }}"
  when: s3cmd_install == 'git'

- name: set fact for packages (pip)
  set_fact:
     s3cmd_pkgs: "{{ s3cmd_pkgs_pip }}"
  when: s3cmd_install == 'pip'



- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: git-install.yml
  when: s3cmd_install == 'git'

- include_tasks: pip-install.yml
  when: s3cmd_install == 'pip'

# - name: Ensure Config path exists
#   file:
#     path: "{{ s3cmd_cfg_path }}"
#     state: directory
#     owner: "root"
#     group: "{{ s3cmd_cfg_group }}"
#     mode: 0775
#     recurse: yes
#   become: true

- name: Set config files location
  template:
    src: "s3cfg.j2"
    dest: "{{ s3cmd_cfg_path }}/{{ s3cmd_cfg_file }}"
    mode: 0600
    owner: "{{ s3cmd_cfg_owner }}"
    group: "{{ s3cmd_cfg_group }}"
  become: true

# - name: Symlink s3cmd executable file.
#   file:
#     src: '/usr/local/bin/s3cmd'
#     dest: '/usr/bin/s3cmd'
#     state: link
