---
# tasks file for s3cmd
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: pkgs
- name: Get s3cmd pkg from github
  git:
    repo: "{{ s3cmd_repo }}"
    dest: "{{ s3cmd_dest }}"
    version: "{{ s3cmd_version }}"
- name: Run installation script
  command: sudo python setup.py install
  args:
    chdir: "{{ s3cmd_dest }}"
- name: Set config files a set location
  template:
    src: s3cfg.j2
    dest: "{{ s3cmd_cfg_path }}"
    mode: 644
